# This file name should be sonar-project.properties
# This file is for stand alone configurations

# defaults to project key 
#sonar.projectName=My project
sonar.projectName=CalculatorProject
# -> For Cloud
sonar.projectKey=PR2309_Calulator_JavaMavenEclipseProject
	#-> For Server
	#sonar.projectKey=CalculatorProject

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

# Disable SCM (Git) to avoid ignoring files
#sonar.scm.exclusions.disabled=true

# defaults to 'not provided'
#sonar.projectVersion=1.0
 
# Path is relative to the sonar-project.properties file. Defaults to .
#sonar.sources=.
sonar.inclusions=**/*.java
#sonar.sources=src
# Source and bytecode locations
sonar.sources=src/main/java
#sonar.java.binaries=target/classes
 

sonar.java.binaries=target/classes

# must be unique in a given SonarQube Server instance
# Replace it with actual token
#-> For Cloud
sonar.token=1585d...
	#-> For Server
	#sonar.token=sqp_ce4b1...


#-> For cloud
sonar.host.url=https://sonarcloud.io
	#-> For Server
	#sonar.host.url=http://localhost:9000

#-> For Cloud
sonar.organization=pr2309

# Optional \u2013 SonarScanner auto-detects, but add if missing
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml